---
version: 2.1

jobs:
  test:
    environment:
      PYTHONPATH: /tmp/project
    working_directory: /tmp/project
    docker:
    - image: matthewschuchard/ansible-module
    resource_class: small
    steps:
    - checkout
    - run:
        name: install dependencies
        command: pip install hvac
    - run:
        name: ruff
        command: ruff check .
    - run:
        name: ty
        command: ty check src

workflows:
  execute_tests:
    jobs:
    - test
